name: build-redmi_ax6-stock-23.05.4 ImmortalWrt

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: "请选择路由器型号"
        required: true
        options:
          - glinet_gl-mt3000
          - glinet_gl-mt2500
          - glinet_gl-mt6000
          - redmi_ax6-stock
        default: redmi_ax6-stock
      include_docker:
        description: "是否编译 Docker 插件"
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'
      enable_pppoe:
        description: "是否配置PPPoE拨号信息?"
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
      pppoe_account:
        description: "宽带账号 (若启用PPPoE)"
        required: false
      pppoe_password:
        description: "宽带密码 (若启用PPPoE)"
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}/mediatek-filogic/build.sh

      - name: Validate PPPoE Inputs
        run: |
          if [[ "${{ github.event.inputs.enable_pppoe }}" == "yes" ]]; then
            if [[ -z "${{ github.event.inputs.pppoe_account }}" || -z "${{ github.event.inputs.pppoe_password }}" ]]; then
              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
              exit 1
            fi
          fi

      - name: Build ImmortalWrt 23.05.4
        run: |
          profiles="${{ github.event.inputs.profile }}"
          include_docker="${{ github.event.inputs.include_docker }}"

          if [ "$profiles" = "redmi_ax6-stock" ]; then
            tag=ipq807x-generic-openwrt-23.05.4
            echo "platform=ipq807x/generic" >> $GITHUB_ENV
          else
            tag=mediatek-filogic-openwrt-23.05.4
            echo "platform=mediatek/filogic" >> $GITHUB_ENV
          fi
          
          IFS=',' read -r -a profile_array <<< "$profiles"
          
          for profile in "${profile_array[@]}"; do
            echo "Building for profile: $profile"
            
            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
              -v "${{ github.workspace }}/glinet:/home/build/immortalwrt/files/etc/uci-defaults" \
              -v "${{ github.workspace }}/mediatek-filogic/build.sh:/home/build/immortalwrt/build.sh" \
              -e PROFILE=$profile \
              -e INCLUDE_DOCKER=$include_docker \
              -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
              -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
              -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
              immortalwrt/imagebuilder:$tag /bin/bash /home/build/immortalwrt/build.sh

      - name: Collect and rename firmware files
        run: |
          mkdir -p ${{ github.workspace }}/release_files
          timestamp=$(date +'%Y-%m-%d-%H-%M-%S')
          echo "release_timestamp=$timestamp" >> $GITHUB_ENV
          cd ${{ github.workspace }}/bin/targets/${{ env.platform }}

          for file in *.bin *.ubi 2>/dev/null; do
            [ -e "$file" ] || continue
            newname="${timestamp}-${{ github.event.inputs.profile }}-${file}"
            cp "$file" "${{ github.workspace }}/release_files/$newname"
          done

      - name: Generate SHA-256 checksums
        run: |
          cd ${{ github.workspace }}/release_files
          for file in *.bin *.ubi; do
            sha256sum "$file" > "$file.sha256"
            sha256sum -c "$file.sha256"
          done

      - name: Upload firmware as GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: Autobuild-${{ env.release_timestamp }}
          name: ImmortalWrt-${{ github.event.inputs.profile }}-${{ env.release_timestamp }}
          files: |
            ${{ github.workspace }}/release_files/*.bin
            ${{ github.workspace }}/release_files/*.ubi
            ${{ github.workspace }}/release_files/*.sha256
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
